[package]
name = "myfs-pack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.5"
rand = "0.8.0"
myfs = { path = "../myfs" }